-- AlterTable
ALTER TABLE `Answer` ADD COLUMN `status` ENUM('NORMAL', 'DELETED') NOT NULL DEFAULT 'NORMAL';

-- AlterTable
ALTER TABLE `Question` ADD COLUMN `level` ENUM('ENTRY', 'MID', 'HIGH') NOT NULL DEFAULT 'ENTRY',
    ADD COLUMN `status` ENUM('NORMAL', 'DELETED') NOT NULL DEFAULT 'NORMAL';
