name: Docker Image CI

on:
  push:
    branches: [ "feat-docker-image" ]
  pull_request:
    branches: [ "feat-docker-image" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build frontend image and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/x86_64
          push: true
          tags: latest
