name: Docker Image CI

on:
  push:
    branches: [ "feat-docker-image" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "feat-docker-image" ]

jobs:
  docker-build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            qmbot/quiz-me-web
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/x86_64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  docker-build-backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v3
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          platforms: linux/x86_64
          push: true
          tags: qmbot/quiz-me-backend:latest
