name: Docker Image CI

on:
  push:
    branches: [ "feat-docker-image" ]
  pull_request:
    branches: [ "feat-docker-image" ]

jobs:
  docker-build-frontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v3
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/x86_64
          push: true
          tags: qmbot/quiz-me-web:latest
  docker-build-backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v3
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          platforms: linux/x86_64
          push: true
          tags: qmbot/quiz-me-backend:latest
